tags:
- name: videos
  description: videos API

paths:
# [GET] videos
  /api/v1/videos:
    get:
      tags:
      - videos
      summary: Find All Videos
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] videos
    post:
      tags:
      - videos
      summary: Add Video
      parameters:
      - name: body
        in: body
        description: video Data
        required: true
        schema:
          $ref: '#/definitions/videos'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] videos/id
  /api/v1/videos/{id}:
    get:
      tags:
      - videos
      summary: Find Video By Id
      parameters:
      - name: id
        in: path
        description: Video Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] videos/id
    put:
      tags:
      - videos
      summary: Update Video By Id
      parameters:
      - name: id
        in: path
        description: video Id
        required: true
      - name: body
        in: body
        description: video Data
        required: true
        schema:
          $ref: '#/definitions/videos'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] videos/id
    delete:
      tags:
      - videos
      summary: Delete Video By Id
      parameters:
      - name: id
        in: path
        description: video Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  videos:
    type: object
    required:
        - title
        - url
        - accessType
        - size
        - ownerId
    properties:
      title:
        type: string
        description: video title
      url:
        type: string
        description: video url
      accessType:
        type: boolean
        description: video access
      size:
        type: number
        description: video size
      ownerId:
        type: string
        description: video owner id

schemes:
 - https
 - http
